server:
  port: 8080

#https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info
info:
  app:
    name: trade tools web container
    description: tomcat container for serving angular client ui.
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/