server:
  port: 9001

#https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info
info:
  app:
    name: watchlist service
    description: watchlist service
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/