server:
  port: 9999

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info
info:
  app:
    name: config server
    description: configuration server.
    version: 1.0.0

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enlightendev/spring-cloud-config